#!/usr/bin/env python3

import sys

from PIL import Image

from grayscale import Grayscale


if len(sys.argv) > 1:
    image = Image.open(sys.argv[1])

    width = None
    if len(sys.argv) > 2:
        width = int(sys.argv[2])

    ascii = Grayscale(image, force_width=width)()
    print(ascii)
